### ISSUE TITLE
Naming of entries is inconsistent with the Navigation Timing API

### ISSUE THREAD

**Issue by thomas-darling** [w3c/paint-timing#18]
The casing of the entry names `first-paint` and `first-contentful-paint` are not consistent with the `Navigation Timing API`, which uses camelCase.

Pointless inconsistencies like this are incredibly frustrating to have in a standard, especially when they are ignored for so long that they start getting out into the wild - case in point, this just shipped in Chrome 60, and we had a bug because we thought the casing of the names was consistent.

https://www.chromestatus.com/feature/5688621814251520

Please resolve this before more browsers and developers are affected by it.

**Comment by igrigorik** [comment]
We have not, historically, camel-cased [entryType](https://w3c.github.io/performance-timeline/#dom-performanceentry-entrytype) names, as such there is no inconsistency here. That said, I do think it's a good idea to spell out some non-normative guidance in the Perf Timeline spec on naming conventions -- let's take that conversation there.

Can you provide more context on your bug?

**Comment by domenic** [comment]
https://w3ctag.github.io/design-principles/#casing-rules

**Comment by igrigorik** [comment]
@domenic ah, you're right, that's where we cribbed it from! ty.

Closing.

**Comment by thomas-darling** [comment]
Really?

It's great that you have guidelines for this now, but since navigation the Navigation Timing API is not following them, neither should this. Those entries all end up in the same array, and having to remember which entries are camelCase and which are not, that is just asking for bugs.

If you some day decide to clean up the casing of _all_ the entry names, then sure, go with the standard casing, whatever that is, but until then, please keep things consistent - because this is just wrong:

```js
performance.measure("navigationStart", "first-paint")
```

You can't seriously expect people to not write "firstPaint" there.

**Comment by igrigorik** [comment]
@thomas-darling NT _is_ following the right conventions: properties are camel-cased, whereas entryType is an enumerated value. What you're highlighting here is a quirk of the User Timing L2 API, which we're hoping to deprecate (the quirk, not the API) in the future -- which is to say, I hear your pain and, yes, it is annoying.
