### ISSUE TITLE
The exact timing of navigation should be defined

### ISSUE THREAD

**Issue by rniwa** [w3c/paint-timing#19]
The definition of [first paint](https://www.w3.org/TR/paint-timing/#first-paint) mentions:
> First Paint entry contains a DOMHighResTimeStamp reporting the time when the browser first rendered after navigation.

However, there are many steps needed to [navigate a browsing context](https://html.spec.whatwg.org/multipage/browsing-the-web.html#navigate). We need to refer to a specific step in the navigation so that there is no ambiguity in terms of whether fragment navigation is included, etc...

**Comment by RiteshMaheshwari** [comment]
+1 on this. Are the first paint and first contentful paint defined as time since navigation_start? If so, can we please clarify it in the documentation.

**Comment by RiteshMaheshwari** [comment]
Thanks for the clarification @Zizzamia . 
> But, it looks like most implementations are treating startTime as duration since some event (likely/hopefully navigationStart). See MDN. My own test on Chrome 65 shows startTime to be in 100s of milliseconds.
So, just to confirm, does this mean chrome is implementing this wrong?

**Comment by tdresser** [comment]
Todd: we can just eliminate "after navigation".
We need to specify some scope though, equivalent to the scope of a time origin.

Something like "First paint after the time origin is set".

**Comment by yoavweiss** [comment]
To clarify @tdresser's comment , the group's decision at TPAC was to better define the time we're after as "First paint after the time origin is set" for the newly navigated document.

**Comment by npm1** [comment]
If this is producing confusion then I think we can replace "These metrics mark the points, immediately after navigation, when the browser renders pixels to the screen." with "These metrics mark the points in time when the browser renders pixels to the screen." Also, the introduction should be marked as non-normative. The fact that these timestamps are relative to the `time origin` is clear from the fact that they are computed by calling `current high resolution time`.

**Comment by rniwa** [comment]
> If this is producing confusion then I think we can replace "These metrics mark the points, immediately after navigation, when the browser renders pixels to the screen." with "These metrics mark the points in time when the browser renders pixels to the screen."

Not mentioning "after navigation" would be an improvement indeed. This sentence has a bunch of other issues but I'm not gonna go into that since that's tracked by other issues.

> Also, the introduction should be marked as non-normative.

Yes! It's very important to distinguish things are normative & things that are not normative.
