### ISSUE TITLE
Define whether clipped contents should be included in first contextual paint

### ISSUE THREAD

**Issue by rniwa** [w3c/paint-timing#20]
[First contextual paint](https://www.w3.org/TR/paint-timing/#first-contentful-paint) says
> non-white canvas or SVG

But verifying that canvas doesn't contain any non-initial pixel or non-clipped text in SVG is expensive. We should re-define in such a way that UA can cheaply determine this by, e.g. not worrying about clipping.

**Comment by tdresser** [comment]
Non-white canvas -> Canvas that has not been drawn to.
Ryosuke proposes just firing for empty SVG's. They should be rare anyways.

**Comment by npm1** [comment]
@noamr will fix this by only waiting for the `context mode` of the canvas, which seems look a reasonable solution.

**Comment by yoavweiss** [comment]
I believe this is now addressed by defining the below as [contentful](https://w3c.github.io/paint-timing/#contentful):
* "target is a canvas with its context mode set to any value other than none"
* "target is an svg element with rendered descendants."

Closing, but feel free to re-open if I'm missing something

**Comment by rniwa** [comment]
Yup, this is fixed.
