### ISSUE TITLE
Add a note in spec about cross-origin check

### ISSUE THREAD

**Issue by spanicker** [w3c/paint-timing#23]
The need for origin check, should be written into the spec.
i.e. paint in cross-origin frames should not mark paint.

**Comment by tdresser** [comment]
I think this will fall out of #22.

I suspect cross-origin frames should behave the same as same origin frames?

We can debate the details there, but I think saying that an iframe counts as FP but not FCP regardless of content is probably correct.

**Comment by npm1** [comment]
I also think there's no difference between how same-origin vs cross-origin frames are handled with PaintTiming. Feel free to close this issue if you agree.

**Comment by spanicker** [comment]
SGTM.
