### ISSUE TITLE
[Question]Some questions about the spec

### ISSUE THREAD

**Issue by NE-SmallTown** [w3c/paint-timing#28]
Rencently I read the doc https://docs.google.com/document/d/1wdxSXo_jctZjdPaJeTtYYFF-rLtUFxrU72_7h9qbQaM  and it's comments, there are a few questions I want to ask:

1. What is FP, FCP, FMP stand for?(Please give more details rather than 'it is happening' or words in the spec because I notice that there are many different opinions on this by reading many issues, docs, posts, slides)

2. What is the accurate time of FP, FCP, FMP be fired, is there any doc describe this? And is there any difference between browers, and could you give me the line number of implemention in source code about this?

3. Does FP in chrome performance panel is same with the FP in the doc?

4. Why there is no FI(first interactive) in the doc?

5. Is there any pic like https://www.w3.org/TR/navigation-timing/timing-overview.png to describe the process about the whole timing which includes FP, FCP, FMP, DOMContentLoaded, Load Event, requestAnimationFrame etc.

6. Why we can just find FP in the performance panel, what about FCP and FMP?

7. What's the workaround's disadvantages in the doc? i.e. 

> Attaching a handler to requestAnimationFrame (and remove it when it fires)
Attach a handler to the onload event of CSS
use on non-standard APIs like chrome.loadtimes’ firstPaint and msFirstPaint
use of other proxy metrics DOM loaded, onload etc. not indicative of paint time

And is there any better way to ployfill the timing api to make we can collect the perf data of our sites?

**Comment by tdresser** [comment]
1. Only First Paint (FP) and First Contentful Paint (FCP) are currently specified in paint timing. First Meaningful Paint (FMP) and First Interactive (FI) are currently unspec'ed, and the working group has no immediate plans to adopt them. 

2. When FP & FCP fire is defined in [the spec](https://github.com/w3c/paint-timing).

3. Yes.

4. Covered in 1.

5. It's a good idea, but tricky to implement. There's no strict ordering for this set of events. For example, FCP could fire either before or after DOMContentLoaded. This makes it hard to make a diagram that isn't misleading. We should put some effort into a decent visualization though.

6. This question is about Chrome, not the paint timing API. That being said, there's an open bug [here](https://bugs.chromium.org/p/chromium/issues/detail?id=749814).

7. There's no great way to polyfill these APIs (hence why we're adding them to the web!). 

* Attaching a handler to requestAnimationFrame (and remove it when it fires)
   * Haven't necessarily drawn anything.
* Attach a handler to the onload event of CSS
   * Not particularly related to when we've drawn stuff.
* use on non-standard APIs like chrome.loadtimes’ firstPaint and msFirstPaint
   * Not available everywhere.
* use of other proxy metrics DOM loaded, onload etc. 
   * Not indicative of paint time

**Comment by NE-SmallTown** [comment]
@tdresser Thanks for your reply!

Could we open this for more discussion or communication?

cc @igrigorik @paulirish @paullewis Very sorry to bother you guys, do you have any thoughts about this? :)

**Comment by igrigorik** [comment]
@NE-SmallTown I agree with all the points in Tim's response. I think he covered all the questions?

**Comment by NE-SmallTown** [comment]
**Q:** What is the accurate time of FP, FCP, FMP be fired, is there any doc describe this? And is there any difference between browers, and could you give me the line number of implemention in source code about this?

**A:** When FP & FCP fire is defined in the spec.

- I thinks this doesn't answer my question
- - At first, the spec just says 'FP: when the browser renders anything that is visually different from what was on the screen prior to navigation'. This is not an **accurate time** because I want to know **when** 'when' in the sentence happen, after immediately the html, css be loaded and parsed? after some the first script or last script or specific script be executed? or something else?
- - Second, And  'that is visually different from what was on the screen prior to navigation' is also ambiguous because I notice that there are some discussion about background, white background, user agent background etc.  
- - And 'FCP: when the browser renders the first bit of content from the DOM', has the same questions above
- And seems the question 'And is there any difference between browers, and could you give me the line number of implemention in source code about this?' doesn't get a reply.
- So that's why I post the question 2

<hr/>

**Q:** Is there any pic like https://www.w3.org/TR/navigation-timing/timing-overview.png to describe the process about the whole timing which includes FP, FCP, FMP, DOMContentLoaded, Load Event, requestAnimationFrame etc.

**A:** It's a good idea, but tricky to implement. There's no strict ordering for this set of events. For example, FCP could fire either before or after DOMContentLoaded. This makes it hard to make a diagram that isn't misleading. We should put some effort into a decent visualization though.

- Why 'There's no strict ordering for this set of events' and why and what scenarios FCP could fire after DOMContentLoaded. And can I find the render strategy about this? It looks like WHATWG and W3C don't have this, I just find eventloop processing model before. (If I am wrong, please let me know, thanks!)

<hr/>
**Q:** Why we can just find FP in the performance panel, what about FCP and FMP?

**A:** This question is about Chrome, not the paint timing API. That being said, there's an open bug here.

- I think this is not a **bug**, it's just a question, and is about paint timing because you say 'yes' when answer the question 'Does FP in chrome performance panel is same with the FP in the doc?' which is also about Chrome.
- I know that the spec should be neutral and should not talk it in any specific broswer or user agent, but you can see that we are just discussing or communicating, we are not putting any comment to the spec. And the member or contributor of any spec come from all kinds of browsers, so I think this is not a aimless question. 

<hr/>

**Q:** Attaching a handler to requestAnimationFrame (and remove it when it fires)
**A:** Haven't necessarily drawn anything.

- Could you explain more details like when or what scenarios it is correct or wrong.
- I append a question '7.5 add a script at head, record the Date.now() and add a script at body and record the Date.now() again, and calculate the difference. (assume there is no script will block the thread)'
- And could you give me a percentage of correctness of these workarounds, e.g. 7.1 maybe is correct in 60% scenarios.


**Sorry** and big **thanks** for reading my wordy words :)

**Comment by tdresser** [comment]
Precise timing of FP & FCP:
* Start [here](https://w3c.github.io/paint-timing/#html-event-loop-processing-model) in the spec. When this happens relative to parsing of CSS, HTML, JS etc isn't consistent, and isn't specced.
* For Chrome, the code is around [here](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/paint/PaintTiming.cpp?dr=CSs&l=143).

Regarding ordering of paint and other events such as DOMContentLoaded - there's nothing tying these together in the spec. An empty webpage will never fire First Paint, but will fire DOMContentLoaded. If that page then inserts some content, First Paint will fire. 

Regarding page load metrics which work well without FP or FCP - this is a pretty complicated topic. If you're looking at a specific site, I'd suggest performing concrete tests. Implement each of your proposed approaches, and see how they compare to FP & FCP. How these metrics perform depends strongly on how your site is architected.

**Comment by NE-SmallTown** [comment]
@tdresser Thanks!

> An empty webpage will never fire First Paint, but will fire DOMContentLoaded. If that page then inserts some content, First Paint will fire.

Ye, that's one scenario, but seems that it is an edge case

> Regarding page load metrics which work well without FP or FCP - this is a pretty complicated topic

Could you give more details about this? I am very interested in this and that's my task theses 2 weeks.

> Implement each of your proposed approaches, and see how they compare to FP & FCP. How these metrics perform depends strongly on how your site is architected.

Ye, but there are 2 questions:

1. Maybe I can't do the all work, that's too heavy, but I will try :)
2. Even I can test it, that's my **own** one site, don't have any persuasive and referential because I want to the metrics in all kinds of devices, platforms, networks and versions. So maybe I can't test it just by myself. And I think maybe you have more objective records about this because you browse or test many many sites. Just like https://docs.google.com/spreadsheets/d/1nGauGA3EvN8NBC3ErWjLd8Bz-NzmmEa6q6UP5KhfgeA does

> How these metrics perform depends strongly on how your site is architected.

Do you have any recommended article which dig into this? If no, could you give me some advice about how to do or start?

Thanks again!

**Comment by tdresser** [comment]
As far as I know, we don't have a comprehensive evaluation of this set of metrics.

As far as articles, you'll probably get some value out of:
https://speedcurve.com/blog/user-timing-and-custom-metrics/
https://www.stevesouders.com/blog/2015/05/12/hero-image-custom-metrics/

**Comment by NE-SmallTown** [comment]
Hi, @tdresser 

The spec says:
> First Contentful Paint entry contains a DOMHighResTimeStamp reporting the time when the browser first rendered any text, image (including background images), non-white canvas or SVG

I want to ask that **when** the browser trigger the **first render**, after render/cssom tree be created? after executed all sync scripts? Is there any difference between devices, browsers, networks, hardware or every time I refresh? How could I dig into this?

**Comment by tdresser** [comment]
As far as I understand, this isn't specified, and browsers use a variety of heuristics to make this decision. I'm not certain where this logic lives in Chrome, and it's likely to be completely different in other browsers.

**Comment by NE-SmallTown** [comment]
Thanks for your quick reply :)

That's say I can't reproduce the actual screenshot even I get all of the timing in performance because it's uncertain, I can't record in the performance panel and make the screenshot when first-paint as the correct one. Does I understand correct?

**Comment by tdresser** [comment]
If you only care about Chrome, using devtools should give you a reasonable idea of what your users see, but there will certainly be some error. I don't have a great sense of how much error there will be though.

**Comment by NE-SmallTown** [comment]
I am a little confused. Even I just care about Chrome, I still think I can't use metrics in performance panel as the correct one, because different users use different devices, which have different speed, os, networks etc. So the devtools is just a reference value, does chrome can promise the metrics is always all the same in all kinds of scenarios?

**Comment by tdresser** [comment]
The metrics and screenshots will not be the same in different scenarios.
