### ISSUE TITLE
Clarify invisible text

### ISSUE THREAD

**Issue by npm1** [w3c/paint-timing#29]
The Paint Timing API says that a paint occurs when the browser has rendered pixels to the screen. Invisible text and whitespaces technically do not cause pixels to be rendered in the screen, but the text can still be highlighted or searched and this would probably cause pixels to be rendered in the screen. It's also not super clear to me how easy it is for browsers to keep track of all invisible text and differentiate it with visible text. The spec should probably clarify whether this kind of text triggers a First Paint and/or a First Contentful Paint. Also, explicit tests should be added to test the behavior when only this kind of text is rendered in a frame.

@tdresser @spanicker let's first agree on what should happen and then I'll send PRs and tests?

**Comment by tdresser** [comment]
We might just have to leave it vague. We should probably spec that FP & FCP should behave the same with respect to invisible text though?

**Comment by igrigorik** [comment]
@npm1 what is our behavior today in Chrome?

**Comment by npm1** [comment]
The following is exposed in Chrome:

- &nbsp: first-paint

- visibility: hidden 'a': first-paint, first-contentful-paint

- visibility: hidden &nbsp: nothing

**Comment by igrigorik** [comment]
Sorry, I meant.. How does Chrome react in response to invisible text? E.g. if I create page with nothing but text on it and a webfont that takes forever to load, what would FP / FCP tell me today?

**Comment by npm1** [comment]
I think the spec says that even First Contentful Paint "includes text with pending webfonts" (but I haven't confirmed Chrome's behavior).

**Comment by irori** [comment]
It seems Chrome triggers FP and FCP on invisible text:
http://output.jsbin.com/lipuzewube/2/quiet

**Comment by tdresser** [comment]
Next step: find a list of cases where we run into whitespaces causing these metrics to fire early.

**Comment by toddreifsteck** [comment]
Discussed at TPAC 2018:
* We agreed that the critical issues are important to specify.
* @tdresser @npm1 @rniwa will review data to determine important white space add to the spec then bring proposal back.

**Comment by npm1** [comment]
I think this will be fixed with https://github.com/w3c/paint-timing/pull/66

**Comment by noamr** [comment]
Can we close this? @npm1
