### ISSUE TITLE
What is the scope of timings?

### ISSUE THREAD

**Issue by domenic** [w3c/paint-timing#31]
As of https://github.com/whatwg/html/pull/3923, the HTML event loop calls "mark paint timings" giving it a `Document` object.

But the spec at https://w3c.github.io/paint-timing/ isn't very clear about how things are scoped. It should probably use the Document argument to make more precise statements like "If this instance of update the rendering is the first contentful paint", and to say in which realm to "Create a new PerformancePaintTiming object"

This problem extends to the called https://w3c.github.io/performance-timeline/#dfn-queue-a-performanceentry spec as well; it's not clear what "For each registered performance observer" means. It could mean any PerformanceObserver objects from any Document at all, or just the Document ones, or the same-origin Document ones...

**Comment by yoavweiss** [comment]
@tdresser / @npm1 - Does this require further discussion? Or is this just work that needs to happen?

**Comment by npm1** [comment]
I think just work that needs to happen? But I agree that the spec is confusing... and I'm not sure what the correct wording is. It says "Each ECMAScript global environment has[...] a list of registered performance observer objects that is initially empty", so we need to tie that with the concept of marking paint timing for a Document.

**Comment by yoavweiss** [comment]
> But the spec at https://w3c.github.io/paint-timing/ isn't very clear about how things are scoped. It should probably use the Document argument to make more precise statements like "If this instance of update the rendering is the first contentful paint", and to say in which realm to "Create a new PerformancePaintTiming object"

I believe these issues are addressed in the current spec language.
@domenic - can you confirm?

> This problem extends to the called https://w3c.github.io/performance-timeline/#dfn-queue-a-performanceentry spec as well; it's not clear what "For each registered performance observer" means. It could mean any PerformanceObserver objects from any Document at all, or just the Document ones, or the same-origin Document ones...

Do I understand correctly that you'd like us to modify "queue a PerformanceEntry" to also receive a document and handle observer registrations off of that? If so, seems like we should open that as an issue on PerformanceTimeline

**Comment by domenic** [comment]
> I believe these issues are addressed in the current spec language. @domenic - can you confirm?

It's mostly fixed. One minor remaining issue is the sentences of the form "If this instance of update the rendering is the first paint of document". [First paint](https://w3c.github.io/paint-timing/#first-paint) is not properly defined on a per-`Document` basis. In fact it seems to not be defined; only "first paint entry" is defined, which is confusing.

> Do I understand correctly that you'd like us to modify "queue a PerformanceEntry" to also receive a document and handle observer registrations off of that? If so, seems like we should open that as an issue on PerformanceTimeline

This looks to have been improved as well. In particular it smuggles in the global object pointer by consulting _newEntry_'s relevant global object, and then it uses that to create all the objects in question. So this seems good to go.

**Comment by npm1** [comment]
> It's mostly fixed. One minor remaining issue is the sentences of the form "If this instance of update the rendering is the first paint of document". [First paint](https://w3c.github.io/paint-timing/#first-paint) is not properly defined on a per-`Document` basis. In fact it seems to not be defined; only "first paint entry" is defined, which is confusing.

Yep, this is related to what I mentioned in https://github.com/w3c/paint-timing/issues/38.

> This looks to have been improved as well. In particular it smuggles in the global object pointer by consulting _newEntry_'s relevant global object, and then it uses that to create all the objects in question. So this seems good to go.

I'm a smuggler :D this is fixed in Paint Timing and I'm tracking others in https://github.com/w3c/performance-timeline/issues/162.

**Comment by yoavweiss** [comment]
> > It's mostly fixed. One minor remaining issue is the sentences of the form "If this instance of update the rendering is the first paint of document". [First paint](https://w3c.github.io/paint-timing/#first-paint) is not properly defined on a per-`Document` basis. In fact it seems to not be defined; only "first paint entry" is defined, which is confusing.
> 
> Yep, this is related to what I mentioned in #38.

Yeah, it seems like whatever will solve #38 will also resolve this.

**Comment by yoavweiss** [comment]
I believe this is closed by #82
