### ISSUE TITLE
The code example incorrectly mentions observing "long tasks"

### ISSUE THREAD

**Issue by philipwalton** [w3c/paint-timing#46]
The [code example in the Paint Timing API](https://www.w3.org/TR/paint-timing/#example) reference an observer observing long tasks. Presumably this is just a copy/paste error, but it should be fixed to avoid any confusion.

**Comment by npm1** [comment]
That has already been fixed, see https://w3c.github.io/paint-timing/#example. The latest published version does contain the error though - not sure if we can add that minor change to the published version @yoavweiss?

**Comment by yoavweiss** [comment]
Paging @plehegar

**Comment by npm1** [comment]
This has been fixed since https://www.w3.org/TR/paint-timing/#example now observes 'paint' as intended, so I'll close this.
