### ISSUE TITLE
First contentful paint should take the poster image / first frame of video into account

### ISSUE THREAD

**Issue by rniwa** [w3c/paint-timing#51]
For the purpose of determining whether a given rendering would result in the first contentful paint, we should take whether there was a video with the first frame / poster image rendered or not since that would result in an user visible content.

**Comment by npm1** [comment]
Agree. And we should add a WPT for this case if there isn't one.

**Comment by rniwa** [comment]
Indeed, a test would be nice.

**Comment by noamr** [comment]
Addressed in https://github.com/w3c/paint-timing/pull/66

**Comment by rniwa** [comment]
I don't think we should be closing these issues until the PR is landed.

**Comment by noamr** [comment]
See https://github.com/w3c/paint-timing/pull/70

**Comment by yoavweiss** [comment]
As #66 and #70 landed, I believe this can be closed. Feel free to reopen if I'm missing something.
