### ISSUE TITLE
Consider taking form controls into account for first contentful paint

### ISSUE THREAD

**Issue by rniwa** [w3c/paint-timing#52]
It's unclear from the current wording of the spec whether text within form control elements such as input element's placeholder is taken into account for the [first contentful paint](https://w3c.github.io/paint-timing/#first-contentful-paint). We need to more precisely define what "browser first rendered any text" means. Since "rendered" or "render" is not a term of art, we need to refer to a more specific CSS concept here.

**Comment by npm1** [comment]
I don't know off the top of my head what the behavior is for these, let's add a WPT. I would agree with taking them into account. Not sure what the problem with the word 'render' is.

**Comment by noamr** [comment]
The spec talks about rendering in terms of "rendering pixels to the screen", I understand from it that "rendered any text" means that the text has appeared on the screen, or the closes possible point to that.

**Comment by rniwa** [comment]
> The spec talks about rendering in terms of "rendering pixels to the screen",

This is too vague of a phrase / sentence to make much sense here. We really need to define

> I understand from it that "rendered any text" means that the text has appeared on the screen, or the closes possible point to that.

Again, this needs to be precisely defined.

The spec has the following text:

> Paint: the browser has performed a "paint" (or "render") when it has converted the render tree to pixels on the screen. This is formally defined as the when update the rendering happens in event loop processing.

First off, "render tree" is not really a concept in any CSS spec as far as I know (maybe it's Blink / WebKit terminology that crept into this spec?; in Gecko the equivalent concept is frame tree). If it is, then it needs to be a definition linked. Second off, it's unclear what it means to *convert* the *render tree* to pixels. We really need to refrain from using these random colloquial terms that don't have any formal definitions in our specifications.

Finally, it's unclear what "update the rendering" refers to. Is this the concept of [updating the rendering](https://html.spec.whatwg.org/multipage/webappapis.html#update-the-rendering) in step 10 of the event loop processing model? Or Are we referring to step 10.14 where we actually update the rendering of each active document.

Now let's dive into the following text in the specification:
> First Contentful Paint entry contains a DOMHighResTimeStamp reporting the time when the browser first rendered any text, image (including background images), non-white canvas or SVG. This excludes any content of iframes, but includes text with pending webfonts. This is the first time users could start consuming page content.

It's unclear what *rendered* means in "rendered any text" since *render* is not a formal concept in CSS. I think the fundamental issue here is that we don't know what it means for something to be painted on screen. That's not really a concept defined anywhere. Filed https://github.com/w3c/csswg-drafts/issues/4825 in CSS to tackle this.

**Comment by noamr** [comment]
How is this: https://github.com/w3c/paint-timing/pull/73

**Comment by yoavweiss** [comment]
@rniwa & @npm1 - can we close this?

**Comment by npm1** [comment]
I think this is solved, feel free to reopen if you think otherwise.
