### ISSUE TITLE
Clarify what happens to a page which consists of just an iframe

### ISSUE THREAD

**Issue by rniwa** [w3c/paint-timing#54]
According to the current definitions of the [first paint](https://w3c.github.io/paint-timing/#first-contentful-paint):
> First Paint entry contains a DOMHighResTimeStamp reporting the time when the browser first rendered after navigation. This excludes the default background paint, but includes non-default background paint and the enclosing box of an iframe. This is the first key moment developers care about in page load – when the browser has started to render the page.
and [first contentful paint](https://w3c.github.io/paint-timing/#first-contentful-paint),
> First Contentful Paint entry contains a DOMHighResTimeStamp reporting the time when the browser first rendered any text, image (including background images), non-white canvas or SVG. This excludes any content of iframes, but includes text with pending webfonts. This is the first time users could start consuming page content.

A web page which consists of a single iframe (i.e. all of page's content appears inside an iframe), would never get first contentful paint even if the iframe was of the same origin. This seems rather broken.

**Comment by npm1** [comment]
I don't agree. Counting same-origin iframe content but not cross-origin content seems more confusing to me. A developer can look at FCP of the iframe.

**Comment by noamr** [comment]
FP/FCP are per frame, I think that's pretty clean.

**Comment by rniwa** [comment]
> FP/FCP are per frame, I think that's pretty clean.

Ok, that’s pretty problematic for WebKit. Because we determine whether a given page is painted or not based on the main frame’s document’s content, exposing this information in cross-origin iframes would result in information leak.

**Comment by noamr** [comment]
> > FP/FCP are per frame, I think that's pretty clean.
> 
> Ok, that’s pretty problematic for WebKit. Because we determine whether a given page is painted or not based on the main frame’s document’s content, exposing this information in cross-origin iframes would result in information leak.

We cab decide that in WebKit a cross-origin frame will not get the paint API (would not even get "paint" as an available entry type). I don't even think the spec needs to change for that :)

**Comment by rniwa** [comment]
> > Ok, that’s pretty problematic for WebKit. Because we determine whether a given page is painted or not based on the main frame’s document’s content, exposing this information in cross-origin iframes would result in information leak.
> 
> We ca[n] decide that in WebKit a cross-origin frame will not get the paint API (would not even get "paint" as an available entry type). I don't even think the spec needs to change for that :)

That should probably be explicitly called out as an option in the spec. But having browser difference like that isn't great for interoperability either.

**Comment by rniwa** [comment]
By the way, reporting the paint time in every frame seems problematic if that paint time can be affected by cross-origin subframe's paint time since that could leak information.

**Comment by npm1** [comment]
Is there no way for WebKit to determine when content in an iframe has painted? It would be great if you could look into it and try to ship paint API for all frames, not just the main frame.

> By the way, reporting the paint time in every frame seems problematic if that paint time can be affected by cross-origin subframe's paint time since that could leak information.

Yea, this is precisely why paint times need to be reported for each frame separately, without considering content from other frames. Reporting paint time on a page level would be problematic because that would consider paints in cross-origin iframes.

**Comment by rniwa** [comment]
> Is there no way for WebKit to determine when content in an iframe has painted? It would be great if you could look into it and try to ship paint API for all frames, not just the main frame.

It’s not a matter of when iframe contents are painted. It’s that the entire painting of a given page is gated by the main frame’s content.

> Reporting paint time on a page level would be problematic because that would consider paints in cross-origin iframes.

Unfortunately, that’s how painting works in WebKit, and we’re not gonna change that anytime soon.

**Comment by noamr** [comment]
> > Reporting paint time on a page level would be problematic because that would consider paints in cross-origin iframes.
> 
> Unfortunately, that’s how painting works in WebKit, and we’re not gonna change that anytime soon.
An additional suggestion for FCP in cross-origin frames: report an FCP that is *not* bound by the main frame, and thus not leaking information. In essence, when its own content was ready to be painted. It would get indication about own performance, but would not be able to tell if the main frame has actually painted it.

**Comment by noamr** [comment]
An additional suggestion for FCP in cross-origin frames: report an FCP that is not bound by the main frame, and thus not leaking information. In essence, when its own content was ready to be painted. It would get indication about own performance, but would not be able to tell if the main frame has actually painted it.

**Comment by rniwa** [comment]
> An additional suggestion for FCP in cross-origin frames: report an FCP that is not bound by the main frame, and thus not leaking information.

I don't think that's something we can or want to implement in WebKit because the painting happens at page level in WebKit inside a [CADisplayLink callback](https://developer.apple.com/documentation/quartzcore/cadisplaylink?language=objc).

**Comment by noamr** [comment]
> > An additional suggestion for FCP in cross-origin frames: report an FCP that is not bound by the main frame, and thus not leaking information.
> 
> I don't think that's something we can or want to implement in WebKit because the painting happens at page level in WebKit inside a [CADisplayLink callback](https://developer.apple.com/documentation/quartzcore/cadisplaylink?language=objc).

Right, I meant reporting the contentful milestone for the frame rather than the actual paint.
But I think as a start omitting paint API for cross-origin frames is good enough.

The wording in the spec should perhaps cover that: "A user agent implementing PerformancePaintTiming would need to include "paint" in supportedEntryTypes for Window contexts." - maybe somehow mention that the result applies to the current frame?

**Comment by rniwa** [comment]
> > > An additional suggestion for FCP in cross-origin frames: report an FCP that is not bound by the main frame, and thus not leaking information.
> > 
> > 
> > I don't think that's something we can or want to implement in WebKit because the painting happens at page level in WebKit inside a [CADisplayLink callback](https://developer.apple.com/documentation/quartzcore/cadisplaylink?language=objc).
> 
> Right, I meant reporting the contentful milestone for the frame rather than the actual paint.

What I'm saying is that this is not possible because we wouldn't know whether we're about to paint without scheduling CADisplayLink, which we would not until the main frame is ready to paint.

> But I think as a start omitting paint API for cross-origin frames is good enough.

The fact spec doesn't currently allow this is problematic.

> The wording in the spec should perhaps cover that: "A user agent implementing PerformancePaintTiming would need to include "paint" in supportedEntryTypes for Window contexts." - maybe somehow mention that the result applies to the current frame?

That's too vague of statement to be a normative text. We'd need to modify the algorithm to [mark paint timing](https://w3c.github.io/paint-timing/#mark-paint-timing) to run the algorithm to [report paint timing](https://w3c.github.io/paint-timing/#report-paint-timing) on with the very document given by the [update the rendering](https://html.spec.whatwg.org/multipage/webappapis.html#update-the-rendering), step 10.13 in the HTML event loop's processing model. Note that the algorithm to report paint timing then needs to create a PerformancePaintTiming object *newEntry* with that document.

It's very much problematic that neither the definition of FP nor FCP defines what frame, document, or CSS boxes in those documents are relevant for a given rendering / paint operation. As things stand, nothing is really well defined in this specification with regards to multiple frames in a given page.

**Comment by noamr** [comment]
Possibly addressed in https://github.com/w3c/paint-timing/pull/79

**Comment by rniwa** [comment]
I think the latest iterations of spec updates and https://github.com/w3c/paint-timing/pull/79 should be sufficient here.

**Comment by noamr** [comment]
https://github.com/w3c/paint-timing/pull/79 has landed, closing.
