### ISSUE TITLE
Combination of paint timing and long tasks can expose precise paint timing

### ISSUE THREAD

**Issue by rniwa** [w3c/paint-timing#55]
[Update the rendering](https://html.spec.whatwg.org/multipage/webappapis.html#update-the-rendering) makes paint timing for each document right before updating the rendering (painting) in step 13 and computes *rendering end time* for reporting long tasks in step 12. Because this sandwitches the painting operation, it can be used to measure the paint time with a high precision.

**Comment by npm1** [comment]
Yes, the longtasks API is meant to expose long paint times. FWIW I don't think we implemented 'long update the rendering' in our longtasks implementation, even though it is specified. You would get a high precision value just using longtasks. This issue would belong in that repo.

**Comment by rniwa** [comment]
Alright, filed https://github.com/w3c/longtasks/issues/80
