### ISSUE TITLE
Clarify contentful state regarding images that are not foreground/background

### ISSUE THREAD

**Issue by noamr** [w3c/paint-timing#56]
For example, mask images should probably be considered contentful.

**Comment by npm1** [comment]
Yep, makes sense. Things to do here: add those to the list of contentful, and add a WPT for that.

**Comment by noamr** [comment]
I would be happy to add the WPT once the spec is modified.

**Comment by noamr** [comment]
Addresses in https://github.com/w3c/paint-timing/pull/66

**Comment by rniwa** [comment]
Please don't close an issue until the relevant PR is landed. It's very confusing.

**Comment by noamr** [comment]
Closing now that the PR has landed. https://w3c.github.io/paint-timing/
