### ISSUE TITLE
Allow optional implementation of first-paint

### ISSUE THREAD

**Issue by noamr** [w3c/paint-timing#57]
Feedback from webkit: current approach is to currently implement first-contentful-paint and not first-paint. That's because first-paint is bound to be different between browsers, and having web developers rely on it may cause unhelpful optimizations. 

The spec should specify what happens in this case, maybe an API to detect which paint milestones the user agent supports.

**Comment by npm1** [comment]
I think there is not much change to be done in the spec in this regard. Perhaps we can add a Note saying that some user agents only implement FCP. As for the way to detect this, perhaps it is sufficient to know that FCP is the last 'paint' entry that is reported. Therefore, if a developer sees FCP but FP is not received, this means that the user agent is not going to provide an FP value. Is that reasonable?

**Comment by noamr** [comment]
I find it reasonable.

**Comment by noamr** [comment]
... once the spec is modified, I'll update WPT to account for the situation where FP is not there.

**Comment by rniwa** [comment]
There might be an issue here though. If Mozilla is also not interested in implementing this metric, then we would never have multiple independent implementations, and it needs to be removed from the spec altogether before we can move forward.

**Comment by anniesullie** [comment]
I spent some time digging into first-paint vs first-contentful-paint on various engines using WebPageTest. Here are the results: https://github.com/anniesullie/FPvsFCP/blob/master/README.md

It definitely looks like some sites optimize for first-paint on browsers that paint earlier, including Firefox.

@bdekoz do you think first-paint is valuable to Mozilla, in addition to first-contentful-paint?

**Comment by bdekoz** [comment]
Is the intent to deprecate first-paint with first-contentful-paint? If so, then there should be normative text that says it.

**Comment by rniwa** [comment]
> Is the intent to deprecate first-paint with first-contentful-paint? If so, then there should be normative text that says it.

The question is if Mozilla is interested in implementing first-paint given WebKit is not since we need two independent implementations to keep anything in the spec.

**Comment by bdekoz** [comment]
Yes.

**Comment by rniwa** [comment]
> Yes.

Yes, as in you’re interested? If so, then it seems like we get to keep the feature in the spec.

I’d say though that WebKit will probably never implement this feature so there isn’t really a path forward to have interoperability across the three major engines here.

**Comment by noamr** [comment]
> > Yes.
> 
> Yes, as in you’re interested? If so, then it seems like we get to keep the feature in the spec.
> 
> I’d say though that WebKit will probably never implement this feature so there isn’t really a path forward to have interoperability across the three major engines here.

Isn't interop around FCP with 3 engines and interop around FP with 2 engines sufficient, as long as the spec defines FP as optional?

**Comment by rniwa** [comment]
>
> > Yes, as in you’re interested? If so, then it seems like we get to keep the feature in the spec.
> > I’d say though that WebKit will probably never implement this feature so there isn’t really a path forward to have interoperability across the three major engines here.
> 
> Isn't interop around FCP with 3 engines and interop around FP with 2 engines sufficient, as long as the spec defines FP as optional?

It's sufficient from W3C shipping criteria. It's bad from the Web platform interoperability perspective because this API would never be supposed across all browsers.

**Comment by gi11es** [comment]
Speaking from a user's perspective, any new paints timings exposed by a browser is progress. That's more important than having all of them on all browsers.

Was this implemented as separate standards for each paint timing, there wouldn't be any debate. eg. Firefox supports the "First Paint API" and Webkit doesn't, they both support the "First Contentful Paint API".

In a way, the grouping under a single standard is for ergonomics, but I think it's perfectly acceptable for support to progress for each paint timing type independently. Because they can be quite different features in terms of implementation. It would block progress to wait for all browsers to support all proposed paint timings before any implementation is done.

**Comment by noamr** [comment]
Maybe the way to deal with this and with https://github.com/w3c/paint-timing/issues/54 is add a more accurate feature-detection API. Maybe `performance.paint.supportedEntryNames()`, which would return 'first-contentful-paint' in Safari when it's the main or a same-origin frame and an empty array in cross-origin frames. In Firefox/Chrome it can return different values.

**Comment by npm1** [comment]
`supportedEntryNames` would make sense for PaintTiming but definitely not for most other APIs where the `name` can be arbitrary, so I don't think we want to have that.

**Comment by noamr** [comment]
> `supportedEntryNames` would make sense for PaintTiming but definitely not for most other APIs where the `name` can be arbitrary, so I don't think we want to have that.

Yes, that's why I suggested to have it inside the `performance.paint` namespace. We can also think of different API naming `supportedPaintEntryNames` ?

**Comment by npm1** [comment]
There is no `performance.paint`, we'd need one just for that method. And in that case the method name is way too generic for what it really intends to capture.

**Comment by noamr** [comment]
> There is no `performance.paint`, we'd need one just for that method. And in that case the method name is way too generic for what it really intends to capture.

Maybe `performance.paint.{ supportsFirstContentfulPaint(); supportsFirstPaint() }` ?
Other suggestions?

**Comment by npm1** [comment]
Hmm `supportedPaintTypes`?

**Comment by noamr** [comment]
> Hmm `supportedPaintTypes`?

The word `type` is maybe over used... `supportedPaintEntries` ?

**Comment by npm1** [comment]
Hmm sorry that the choice of `type` is confusing. We already have `supportedEntryTypes` so I was being consistent with that. But I guess your suggestion is OK too.

**Comment by noamr** [comment]
Following the discussion in the WG, can we close this? Is a non-normative note needed?

**Comment by npm1** [comment]
I believe we need normative text stating that a user agent is allowed to not implement 'first-paint'.

**Comment by npm1** [comment]
This plus fixing all of the existing tests to account for that fact :) I can work on that soon.

**Comment by noamr** [comment]
How is this for the spec change? https://github.com/w3c/paint-timing/pull/81
OF course the tests still need fixing etc :)

**Comment by noamr** [comment]
https://github.com/w3c/paint-timing/pull/81 has landed, closing the issue, feel free to reopen.
