### ISSUE TITLE
PerformanceTimeline or NavigationTiming support

### ISSUE THREAD

**Issue by nicjansma** [w3c/paint-timing#6]
Because it isn't yet mentioned explicitly in the README, I wanted to make sure these events won't be _only_ consumable by `PerformanceObserver`.  We should be able to fetch them from the `PerformanceTimeline` 
 as well, correct?  (or my preference, alongside NavigationTiming)

My thought is if we're going to expose new page lifecycle timestamps, we should make sure they can be read at any time after they've happened, just like all of the other NavTiming timestamps.  That would make it friendly for RUM, or just for a developer opening their dev tools after-the-fact who wants to compare them to other timestamps.

Since we're talking about a handful of entries, I think it would be reasonable to put them in the PerformanceTimeline with no buffer management and no timeout (e.g. not removed at `onload`)

> Why not add this to Navigation Timing?
> This belongs outside Navigation Timing because Navigation Timing is spec'd as queueing the entry on document load end, however FCP (or FMP in the future) may not have triggered at that point.

I understand the concern, but it really *feels* like they belong alongside NavTiming.  I know we're moving away from NavTiming1 (`performance.timing`), but that really is the perfect place to add these, since those are the rest of the page-lifecycle timestamps, and there's no explicit entry-queuing time to worry about.  The downside is they're obviously not in DOMHighRes format.

We could still put them in NavTiming2 (PerformanceTimeline), and if they didn't happen at onload, they would just be 0.

It just seems strange to me to point people to NavTiming for most of their page-lifecycle timestamps, but have to get two or three timestamps from somewhere else.

**Comment by spanicker** [comment]
<< We should be able to fetch them from the PerformanceTimeline as well, correct?
Yes - this will support the perf timeline spec update to buffer entries until onload.

Good question on why this shouldn't just be merged with NT2, we were bit conservative as we expect to add more timestamps down the road like TTI - which might not logically belong in "navigation"

**Comment by nicjansma** [comment]
So these entries will _only_ be in the PerformanceTimeline until `onload`?  If there are just a small handful of them, why would we clear them at `onload`?

I still think that all of these timestamps like FP/FCP/FMP/TTI are all part of the "navigation" -- they happen once per navigation.  We don't have to stop exposing timestamps of interesting events at `onload`.

**Comment by spanicker** [comment]
These entries will remain buffered and never be cleared. This is already implemented (and shipping) in M60, could you try it out and report any issues?

@igrigorik to comment on exposing these on Navigation Timing.

**Comment by nicjansma** [comment]
Awesome, "_... buffer entries until onload_" was referring to PerformanceObserver? 

These entries are available in the PerformanceTimeline after `onload` as desired:

![image](https://cloud.githubusercontent.com/assets/1004649/26643316/ef33add4-45fe-11e7-8601-2e21118f60cf.png)

**Comment by igrigorik** [comment]
> I still think that all of these timestamps like FP/FCP/FMP/TTI are all part of the "navigation" -- they happen once per navigation. We don't have to stop exposing timestamps of interesting events at onload.

Separate records means you can get separate notifications for each one, without polling for them. Instead, let's say we put all of these timestamps onto NT.. how do you know when the new metric is available, especially if we have timestamps beyond onload? FWIW, I think we should err on the side of many individual entries, as opposed to uber-entries that contain all the timestamps.. which is to say, my vote is to keep Paint Timing separate from NT.

**Comment by nicjansma** [comment]
I like that there are separate paint records via PO as well.

I think it would be useful to put the timestamps on `performance.timing` in addition to PO/PT, but I realize it would complicate the dance between the two specs (especially since `performance.timing` is now deprecated).

For RUM, we generally don't need notification of new document lifecycle timestamps, as we'll just collect whatever is available at the time we need to send the beacon (we're not polling `performance.timing` for new data, it's just read as-is at beacon).  Having the timestamps on `performance.timing` just makes all of the data available in one place, versus querying `performance.timing` then querying `performance.getEntriesByType("paint")` (if we don't already have PaintTiming data from listening via PO).

So my concern is mostly along the lines of ease-of-use, and if you think it'll complicate the specs too much, we can live with the data being just on PT/PO, and close out this issue.

**Comment by igrigorik** [comment]
With benefit of hindsight, I think if we were building NT/RT from scratch, I'd suggest that we package each timestamp into a separate record -- i.e. similar to what we're doing here with paint -- because that allows us to report progress without forcing consumers to either (a) poll the partial record, or (b) defer the record until all timestamps are "ready".  Who knows, maybe in RT L3.. :-)

I'll close this with no action, I think current behavior (separate records) is good tradeoff between developer ergonomics and perf-timeline coherency, and we shouldn't couple paint timing to NT/RT.
