### ISSUE TITLE
Account for typographical pseudo-elements

### ISSUE THREAD

**Issue by noamr** [w3c/paint-timing#77]
The case where, for example, a text is visible but its `::first-line` is marked with `opacity: 0`, and the text has only one line, would generate FCP with the current spec. The same applies for `::first-letter`.

https://www.w3.org/TR/css-pseudo-4/#typographic-pseudos

**Comment by rniwa** [comment]
How about ::selection?

**Comment by noamr** [comment]
Yes, probably ::selection should also be considered.

**Comment by noamr** [comment]
> Yes, probably ::selection should also be considered.

Actually, after the last WG discussion I believe ::selection should be ignored as it's interactivity-based.

**Comment by noamr** [comment]
Closing, now that https://github.com/w3c/paint-timing/pull/80 has landed. Feel free to reopen.
